import { AgeRating, Genre, Platform, Prisma } from '@prisma/client'

export const GAMES: Prisma.GameCreateManyInput[] = [
	{
		title: 'The Witcher 3: Wild Hunt',
		genres: [Genre.RPG, Genre.Action],
		platforms: [
			Platform.PC,
			Platform.PlayStation,
			Platform.Xbox,
			Platform.Nintendo
		],
		releaseDate: new Date('2015-05-19'),
		price: 39.99,
		rating: 9.5,
		ageRating: AgeRating.M,
		developer: 'CD Projekt Red',
		publisher: 'CD Projekt',
		image: '/uploads/games/witcher.jpg'
	},
	{
		title: 'Red Dead Redemption 2',
		genres: [Genre.Action, Genre.Adventure],
		platforms: [Platform.PC, Platform.PlayStation, Platform.Xbox],
		releaseDate: new Date('2018-10-26'),
		price: 59.99,
		rating: 9.7,
		ageRating: AgeRating.M,
		developer: 'Rockstar Games',
		publisher: 'Rockstar Games',
		image: '/uploads/games/rdr.jpg'
	},
	{
		title: 'Cyberpunk 2077',
		genres: [Genre.RPG, Genre.Action],
		platforms: [Platform.PC, Platform.PlayStation, Platform.Xbox],
		releaseDate: new Date('2020-12-10'),
		price: 59.99,
		rating: 7.5,
		ageRating: AgeRating.M,
		developer: 'CD Projekt Red',
		publisher: 'CD Projekt',
		image: '/uploads/games/cyber.jpg'
	},
	{
		title: 'God of War (2018)',
		genres: [Genre.Action, Genre.Adventure],
		platforms: [Platform.PC, Platform.PlayStation],
		releaseDate: new Date('2018-04-20'),
		price: 49.99,
		rating: 9.8,
		ageRating: AgeRating.M,
		developer: 'Santa Monica Studio',
		publisher: 'Sony Interactive Entertainment',
		image: '/uploads/games/gow.jpg'
	},
	{
		title: 'The Last of Us Part II',
		genres: [Genre.Action, Genre.Adventure],
		platforms: [Platform.PlayStation],
		releaseDate: new Date('2020-06-19'),
		price: 59.99,
		rating: 9.3,
		ageRating: AgeRating.M,
		developer: 'Naughty Dog',
		publisher: 'Sony Interactive Entertainment',
		image: '/uploads/games/last.jpg'
	},
	{
		title: 'Horizon Zero Dawn',
		genres: [Genre.Action, Genre.RPG],
		platforms: [Platform.PC, Platform.PlayStation],
		releaseDate: new Date('2017-02-28'),
		price: 49.99,
		rating: 9.0,
		ageRating: AgeRating.T,
		developer: 'Guerrilla Games',
		publisher: 'Sony Interactive Entertainment',
		image: '/uploads/games/horizon.jpg'
	},
	{
		title: 'Grand Theft Auto V',
		genres: [Genre.Action, Genre.Adventure],
		platforms: [Platform.PC, Platform.PlayStation, Platform.Xbox],
		releaseDate: new Date('2013-09-17'),
		price: 29.99,
		rating: 9.8,
		ageRating: AgeRating.M,
		developer: 'Rockstar North',
		publisher: 'Rockstar Games',
		image: '/uploads/games/gta.jpg'
	},
	{
		title: 'The Legend of Zelda: Breath of the Wild',
		genres: [Genre.Adventure, Genre.Action],
		platforms: [Platform.Nintendo],
		releaseDate: new Date('2017-03-03'),
		price: 59.99,
		rating: 9.7,
		ageRating: AgeRating.E10Plus,
		developer: 'Nintendo EPD',
		publisher: 'Nintendo',
		image: '/uploads/games/zelda.jpg'
	},
	{
		title: 'Dark Souls III',
		genres: [Genre.Action, Genre.RPG],
		platforms: [Platform.PC, Platform.PlayStation, Platform.Xbox],
		releaseDate: new Date('2016-03-24'),
		price: 49.99,
		rating: 9.2,
		ageRating: AgeRating.M,
		developer: 'FromSoftware',
		publisher: 'Bandai Namco Entertainment',
		image: '/uploads/games/dark-souls.jpg'
	},
	{
		title: 'DOOM Eternal',
		genres: [Genre.Action, Genre.Shooter],
		platforms: [
			Platform.PC,
			Platform.PlayStation,
			Platform.Xbox,
			Platform.Nintendo
		],
		releaseDate: new Date('2020-03-20'),
		price: 59.99,
		rating: 8.9,
		ageRating: AgeRating.M,
		developer: 'id Software',
		publisher: 'Bethesda Softworks',
		image: '/uploads/games/doom.jpg'
	},
	{
		title: "Assassin's Creed Valhalla",
		genres: [Genre.Action, Genre.RPG],
		platforms: [Platform.PC, Platform.PlayStation, Platform.Xbox],
		releaseDate: new Date('2020-11-10'),
		price: 59.99,
		rating: 8.5,
		ageRating: AgeRating.M,
		developer: 'Ubisoft Montreal',
		publisher: 'Ubisoft',
		image: '/uploads/games/assassins.jpg'
	},
	{
		title: 'Ghost of Tsushima',
		genres: [Genre.Action, Genre.Adventure],
		platforms: [Platform.PlayStation],
		releaseDate: new Date('2020-07-17'),
		price: 59.99,
		rating: 9.2,
		ageRating: AgeRating.M,
		developer: 'Sucker Punch Productions',
		publisher: 'Sony Interactive Entertainment',
		image: '/uploads/games/ghost.jpg'
	},
	{
		title: "Marvel's Spider-Man",
		genres: [Genre.Action, Genre.Adventure],
		platforms: [Platform.PC, Platform.PlayStation],
		releaseDate: new Date('2018-09-07'),
		price: 49.99,
		rating: 9.0,
		ageRating: AgeRating.T,
		developer: 'Insomniac Games',
		publisher: 'Sony Interactive Entertainment',
		image: '/uploads/games/spider.jpg'
	},
	{
		title: 'Final Fantasy VII Remake',
		genres: [Genre.RPG, Genre.Action],
		platforms: [Platform.PlayStation, Platform.PC],
		releaseDate: new Date('2020-04-10'),
		price: 59.99,
		rating: 9.1,
		ageRating: AgeRating.T,
		developer: 'Square Enix',
		publisher: 'Square Enix',
		image: '/uploads/games/ff.jpg'
	},
	{
		title: 'Resident Evil Village',
		genres: [Genre.Horror, Genre.Action],
		platforms: [Platform.PC, Platform.PlayStation, Platform.Xbox],
		releaseDate: new Date('2021-05-07'),
		price: 59.99,
		rating: 8.4,
		ageRating: AgeRating.M,
		developer: 'Capcom',
		publisher: 'Capcom',
		image: '/uploads/games/village.jpg'
	},
	{
		title: 'Sekiro: Shadows Die Twice',
		genres: [Genre.Action, Genre.Adventure],
		platforms: [Platform.PC, Platform.PlayStation, Platform.Xbox],
		releaseDate: new Date('2019-03-22'),
		price: 59.99,
		rating: 9.5,
		ageRating: AgeRating.M,
		developer: 'FromSoftware',
		publisher: 'Activision',
		image: '/uploads/games/sekiro.jpg'
	},
	{
		title: 'Death Stranding',
		genres: [Genre.Adventure, Genre.Action],
		platforms: [Platform.PC, Platform.PlayStation],
		releaseDate: new Date('2019-11-08'),
		price: 59.99,
		rating: 8.6,
		ageRating: AgeRating.M,
		developer: 'Kojima Productions',
		publisher: 'Sony Interactive Entertainment',
		image: '/uploads/games/death.jpg'
	},
	{
		title: 'Control',
		genres: [Genre.Action, Genre.Adventure],
		platforms: [Platform.PC, Platform.PlayStation, Platform.Xbox],
		releaseDate: new Date('2019-08-27'),
		price: 39.99,
		rating: 8.8,
		ageRating: AgeRating.M,
		developer: 'Remedy Entertainment',
		publisher: '505 Games',
		image: '/uploads/games/control.jpg'
	},
	{
		title: 'Metro Exodus',
		genres: [Genre.Action, Genre.Shooter],
		platforms: [Platform.PC, Platform.PlayStation, Platform.Xbox],
		releaseDate: new Date('2019-02-15'),
		price: 39.99,
		rating: 8.5,
		ageRating: AgeRating.M,
		developer: '4A Games',
		publisher: 'Deep Silver',
		image: '/uploads/games/metro.jpg'
	},
	{
		title: 'Doom (2016)',
		genres: [Genre.Action, Genre.Shooter],
		platforms: [Platform.PC, Platform.PlayStation, Platform.Xbox],
		releaseDate: new Date('2016-05-13'),
		price: 19.99,
		rating: 8.7,
		ageRating: AgeRating.M,
		developer: 'id Software',
		publisher: 'Bethesda Softworks',
		image: '/uploads/games/doom.jpg'
	},
	{
		title: 'Overwatch',
		genres: [Genre.Shooter, Genre.Action],
		platforms: [Platform.PC, Platform.PlayStation, Platform.Xbox],
		releaseDate: new Date('2016-05-24'),
		price: 39.99,
		rating: 8.9,
		ageRating: AgeRating.T,
		developer: 'Blizzard Entertainment',
		publisher: 'Blizzard Entertainment',
		image: '/uploads/games/overwatch.jpg'
	},
	{
		title: 'Battlefield V',
		genres: [Genre.Shooter, Genre.Action],
		platforms: [Platform.PC, Platform.PlayStation, Platform.Xbox],
		releaseDate: new Date('2018-11-20'),
		price: 49.99,
		rating: 8.0,
		ageRating: AgeRating.M,
		developer: 'DICE',
		publisher: 'Electronic Arts',
		image: '/uploads/games/battlefield.jpg'
	},
	{
		title: 'The Elder Scrolls V: Skyrim',
		genres: [Genre.RPG, Genre.Adventure],
		platforms: [
			Platform.PC,
			Platform.PlayStation,
			Platform.Xbox,
			Platform.Nintendo
		],
		releaseDate: new Date('2011-11-11'),
		price: 39.99,
		rating: 9.6,
		ageRating: AgeRating.M,
		developer: 'Bethesda Game Studios',
		publisher: 'Bethesda Softworks',
		image: '/uploads/games/skyrim.jpg'
	},
	{
		title: 'Monster Hunter: World',
		genres: [Genre.Action, Genre.RPG],
		platforms: [Platform.PC, Platform.PlayStation, Platform.Xbox],
		releaseDate: new Date('2018-01-26'),
		price: 49.99,
		rating: 9.0,
		ageRating: AgeRating.T,
		developer: 'Capcom',
		publisher: 'Capcom',
		image: '/uploads/games/monster.jpg'
	},
	{
		title: 'Far Cry 5',
		genres: [Genre.Action, Genre.Shooter],
		platforms: [Platform.PC, Platform.PlayStation, Platform.Xbox],
		releaseDate: new Date('2018-03-27'),
		price: 49.99,
		rating: 8.5,
		ageRating: AgeRating.M,
		developer: 'Ubisoft Montreal',
		publisher: 'Ubisoft',
		image: '/uploads/games/farcry.jpg'
	},
	{
		title: 'Halo Infinite',
		genres: [Genre.Shooter, Genre.Action],
		platforms: [Platform.PC, Platform.Xbox],
		releaseDate: new Date('2021-12-08'),
		price: 59.99,
		rating: 8.7,
		ageRating: AgeRating.T,
		developer: '343 Industries',
		publisher: 'Xbox Game Studios',
		image: '/uploads/games/halo.jpg'
	},
	{
		title: 'Forza Horizon 4',
		genres: [Genre.Action],
		platforms: [Platform.PC, Platform.Xbox],
		releaseDate: new Date('2018-10-02'),
		price: 59.99,
		rating: 9.2,
		ageRating: AgeRating.E,
		developer: 'Playground Games',
		publisher: 'Microsoft Studios',
		image: '/uploads/games/forza.jpg'
	},
	{
		title: 'Persona 5',
		genres: [Genre.RPG, Genre.Adventure],
		platforms: [Platform.PlayStation],
		releaseDate: new Date('2016-09-15'),
		price: 59.99,
		rating: 9.7,
		ageRating: AgeRating.T,
		developer: 'Atlus',
		publisher: 'Atlus',
		image: '/uploads/games/persona.jpg'
	},
	{
		title: 'Yakuza: Like a Dragon',
		genres: [Genre.RPG, Genre.Action],
		platforms: [Platform.PC, Platform.PlayStation, Platform.Xbox],
		releaseDate: new Date('2020-11-10'),
		price: 59.99,
		rating: 8.9,
		ageRating: AgeRating.M,
		developer: 'Ryu Ga Gotoku Studio',
		publisher: 'Sega',
		image: '/uploads/games/yakuza.jpg'
	},
	{
		title: 'Nioh 2',
		genres: [Genre.Action, Genre.RPG],
		platforms: [Platform.PC, Platform.PlayStation],
		releaseDate: new Date('2020-03-13'),
		price: 49.99,
		rating: 9.0,
		ageRating: AgeRating.M,
		developer: 'Team Ninja',
		publisher: 'Koei Tecmo',
		image: '/uploads/games/nioh.jpg'
	}
]
